name: transcendentLIFE
favicon: null
layout_spectrum: 0.74769
typography_spectrum: 0.8290806917939335
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: transcendentLIFE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f1ec'
    - '#2a272e'
    - '#4d5270'
    - '#c4c5bf'
    - '#b45134'
  brandStrength: 0.8526243953965604
  lightness: 0.07157792942598462
  saturation: 0.9216039024759084
  rhythmicContrast: 0.4229940767399967
purpose: []
